there is some sort of error in the sdf itself, here is the traceback from executing:
Traceback (most recent call last):
  File /Users/lkv206/work/to_do_projects/chembl_ligands/grids_lit-pcba/debug_litpcba_111.py, line 92, in <module>
    active_sdf = sdf_to_df((file_path_sdf_active, active))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File /Users/lkv206/work/to_do_projects/chembl_ligands/grids_lit-pcba/debug_litpcba_111.py, line 42, in sdf_to_df
    mol_supplier = Chem.SDMolSupplier(file)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
OSError: File error: Bad input file /Users/lkv206/work/to_do_projects/chembl_ligands/grids_lit-pcba/ADRB2/ADRB2-4lde_active_docking_lib_sorted.sdf

need to check the actual sdf file